"""Generate Pydantic model source from a domain model."""

from __future__ import annotations

from ontolog.export.formats import ExportFormat
from ontolog.export.options import ExportOptions
from ontolog.export.type_map import (
    pydantic_names_for,
    python_field_type,
    python_imports_for,
    type_description_for,
)
from ontolog.export.view import export_view
from ontolog.models.domain import Entity, Field, ProbabilisticDomainModel


def _class_name(entity: Entity) -> str:
    return entity.name.replace(" ", "")


def _entity_class(entity: Entity) -> str:
    return (
        f"class {_class_name(entity)}(BaseModel):\n"
        f'    """Inferred entity (confidence={entity.confidence:.2f})."""\n'
        "\n"
        "    model_config = ConfigDict(frozen=True)\n"
    )


def _field_lines(fields: tuple[Field, ...]) -> list[str]:
    lines: list[str] = []
    for field in fields:
        mapping = python_field_type(field.type_name.value)
        description = type_description_for(field.type_name.value)
        field_args = [f"description={description!r}"]
        if mapping.field_pattern is not None:
            field_args.append(f"pattern={mapping.field_pattern!r}")
        args = ", ".join(field_args)
        lines.append(f"    {field.name}: {mapping.annotation} = Field({args})")
    return lines


def _domain_fields_class(fields: tuple[Field, ...]) -> str:
    if not fields:
        return ""
    body = "\n".join(_field_lines(fields))
    return (
        "class DomainFields(BaseModel):\n"
        '    """Inferred log fields."""\n'
        "\n"
        "    model_config = ConfigDict(frozen=True)\n"
        f"{body}\n"
    )


def _build_source(model: ProbabilisticDomainModel, options: ExportOptions) -> str:
    view = export_view(model, options)
    type_slugs = {field.type_name.value for field in view.fields}
    imports = python_imports_for(type_slugs)
    pydantic_extras = pydantic_names_for(type_slugs)
    pydantic_imports = sorted({"BaseModel", "ConfigDict", "Field", *pydantic_extras})
    lines = [
        '"""Generated by ontolog — do not edit."""',
        "",
    ]
    if imports:
        lines.extend(imports)
        lines.append("")
    lines.extend(
        [
            f"from pydantic import {', '.join(pydantic_imports)}",
            "",
            "",
        ],
    )
    for entity in view.entities:
        lines.append(_entity_class(entity))
        lines.append("")
    domain_fields = _domain_fields_class(view.fields)
    if domain_fields:
        lines.append(domain_fields)
    return "\n".join(lines).rstrip() + "\n"


class PydanticGenExporter:
    """Export a domain model as generated Pydantic source code."""

    @property
    def format_name(self) -> ExportFormat:
        """Return the exporter format identifier."""
        return ExportFormat.PYDANTIC

    def export(
        self,
        model: ProbabilisticDomainModel,
        *,
        options: ExportOptions,
    ) -> str:
        """Return importable Python source for ``model``."""
        return _build_source(model, options)
